branches:
  except:
    - page-source
    - gh-pages

language: python
python:
  - "2.6"
  - "2.7"
env:
  # oldest working via pypi
  - TWISTED_VERSION=9.0.0
  # Debian Squeeze
  - TWISTED_VERSION=10.1.0
  # Ubuntu Precise
  - TWISTED_VERSION=11.1.0
  # Debian Wheezy
  - TWISTED_VERSION=12.0.0
  # Red Hat Enterprise Linux 7
  - TWISTED_VERSION=12.2.0
  # Ubuntu Trusty, Debian Wheezy Backports
  - TWISTED_VERSION=13.2.0
  # Debian Jessie, Ubuntu Vivid
  - TWISTED_VERSION=14.0.2
  # Debian Strech, Ubuntu Wily
  - TWISTED_VERSION=15.2.1
# command to install dependencies
install:
  - pip install pep8
  - pip install Twisted==$TWISTED_VERSION --use-mirrors
  - pip install psycopg2
  - pip install MySQL-python
  - pip install matplotlib
  - pip install -r requirements.txt --use-mirrors
  - mkdir -p $HOME/bin/
  - wget -O $HOME/bin/my_virtualenv https://raw.github.com/evgeni/my_virtualenv/master/my_virtualenv
  - chmod +x $HOME/bin/my_virtualenv
# command to run tests
script:
  - python setup.py install --root=/tmp/bley
  - PATH=$HOME/bin:$PATH make test
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
