branches:
  except:
    - page-source
    - gh-pages

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "2.7"
env:
  # Ubuntu Precise
  - TWISTED_VERSION=11.1.0
  # Debian Wheezy
  - TWISTED_VERSION=12.0.0
  # Red Hat Enterprise Linux 7
  - TWISTED_VERSION=12.2.0
  # Ubuntu Trusty, Debian Wheezy Backports
  - TWISTED_VERSION=13.2.0
  # Debian Jessie, Ubuntu Vivid
  - TWISTED_VERSION=14.0.2
  # Ubuntu Xenial
  - TWISTED_VERSION=16.0.0
  # Debian Jessie Backports
  - TWISTED_VERSION=16.2.0
  # Ubuntu Yakkety, Zesty
  - TWISTED_VERSION=16.4.1
  # Debian Stretch, Debian Sid
  - TWISTED_VERSION=16.6.0
  # latest upstream
  - TWISTED_VERSION=17.1.0
matrix:
  exclude:
    - python: "3.4"
      env: TWISTED_VERSION=11.1.0
    - python: "3.4"
      env: TWISTED_VERSION=12.0.0
    - python: "3.4"
      env: TWISTED_VERSION=12.2.0
    - python: "3.4"
      env: TWISTED_VERSION=13.2.0
    - python: "3.4"
      env: TWISTED_VERSION=14.0.2
    - python: "3.4"
      env: TWISTED_VERSION=16.0.0
    - python: "3.4"
      env: TWISTED_VERSION=16.2.0
    - python: "3.5"
      env: TWISTED_VERSION=11.1.0
    - python: "3.5"
      env: TWISTED_VERSION=12.0.0
    - python: "3.5"
      env: TWISTED_VERSION=12.2.0
    - python: "3.5"
      env: TWISTED_VERSION=13.2.0
    - python: "3.5"
      env: TWISTED_VERSION=14.0.2
    - python: "3.5"
      env: TWISTED_VERSION=16.0.0
    - python: "3.5"
      env: TWISTED_VERSION=16.2.0
    - python: "3.6"
      env: TWISTED_VERSION=11.1.0
    - python: "3.6"
      env: TWISTED_VERSION=12.0.0
    - python: "3.6"
      env: TWISTED_VERSION=12.2.0
    - python: "3.6"
      env: TWISTED_VERSION=13.2.0
    - python: "3.6"
      env: TWISTED_VERSION=14.0.2
    - python: "3.6"
      env: TWISTED_VERSION=16.0.0
    - python: "3.6"
      env: TWISTED_VERSION=16.2.0
# command to install dependencies
install:
  - pip install tox-travis
  - mkdir -p $HOME/bin/
  - wget -O $HOME/bin/my_virtualenv https://raw.github.com/evgeni/my_virtualenv/master/my_virtualenv
  - chmod +x $HOME/bin/my_virtualenv
# command to run tests
script:
  - PATH=$HOME/bin:$PATH tox
  - python setup.py install --root=/tmp/bley
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
